import { RIWAYAT, loadRiwayah, arabicDigits, stripPrefix, searchRows, juzStartPages } from './quran.js';
import { loadReciters, recitationsForRiwayah, audioUrl } from './mp3quran.js';
import { fetchTafsirBooks, fetchTafsir, fetchTranslations, searchQuranpedia, HADITH_BOOKS, fetchHadithEdition } from './content.js';
import { getPrayerTimes, nextPrayer } from './prayer.js';
import * as Store from './storage.js';
import { auth, db, isAdmin, ensureUserProfile, cloudSaveUser, cloudSaveList, cloudLoadList, firebaseApi } from './firebase.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={riwayah:localStorage.getItem('samee3:riwayah')||'hafs',page:Number(localStorage.getItem('samee3:page')||1),fontSize:Number(localStorage.getItem('samee3:fontSize')||38),theme:localStorage.getItem('samee3:theme')||'gold',immersive:true,book:null,selectedAyah:null,reciters:[],filteredReciters:[],audioRec:null,user:null,admin:false,notes:[],bookmarks:[],playlists:[],currentView:'mushaf',searchType:'all',settings:{}};
const audio=$('#audio');

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function save(k,v){localStorage.setItem(`samee3:${k}`,String(v));}
function applySettings(){document.documentElement.style.setProperty('--reader-size',`${state.fontSize}px`);$('.shell').dataset.theme=state.theme;save('fontSize',state.fontSize);save('theme',state.theme);}
function openModal(sel){const el=$(sel);el.classList.add('open');el.setAttribute('aria-hidden','false')}
function closeModal(sel){const el=$(sel);el.classList.remove('open');el.setAttribute('aria-hidden','true')}
function immersiveToggle(force=null){state.immersive=force===null?!state.immersive:force;$('.shell').classList.toggle('immersive',state.immersive)}

async function bootstrap(){
  applySettings();
  $('#fontRange').value=state.fontSize; $('#themeSelect').value=state.theme; $('#riwayahSelect').innerHTML=Object.entries(RIWAYAT).map(([id,v])=>`<option value="${id}">${v.label}</option>`).join(''); $('#riwayahSelect').value=state.riwayah;
  await loadQuran();
  try{state.reciters=await loadReciters();renderReciters();}catch(e){toast('تعذر تحميل قائمة القراء الآن')}
  setupAuth(); setupPrayer(); setupEvents(); restoreLists();
}
async function loadQuran(){state.book=await loadRiwayah(state.riwayah);state.page=Math.max(1,Math.min(604,state.page));save('riwayah',state.riwayah);renderPage(state.page);renderSurahSelects();}
function pageRows(p){return state.book.pages.get(p)||[]}
function makeAyahHTML(a){const txt=(a.aya_text||'').trim();return `<span class="ayah" data-id="${a.id}" data-s="${a.sora}" data-a="${a.aya_no}">${escapeHTML(txt)}<span class="ayah-num">${arabicDigits(a.aya_no)}</span></span> `}
function renderPage(p){
  if(!state.book)return; state.page=Math.max(1,Math.min(604,p));save('page',state.page);
  renderOne($('#pageBefore'),state.page-1,false);renderOne($('#pageCurrent'),state.page,true);renderOne($('#pageAfter'),state.page+1,false);
  const first=pageRows(state.page)[0]; const surah=first?stripPrefix(first.name):'المصحف'; const juz=first?.jozz||1;
  $('#surahTop').textContent=surah;$('#readerMeta').textContent=`الجزء ${arabicDigits(juz)} · الحزب ${arabicDigits(Math.ceil(juz*4))}`;$('#dockSurah').textContent=surah;$('#pageCurrent').dataset.page=state.page;
}
function renderOne(el,p,isCurrent){
  const rows=pageRows(p); el.innerHTML=''; el.className=`mushaf-page ${isCurrent?'page-current':'page-secondary'}`; if(p<1||p>604)return;
  const first=rows[0]; const head=first?stripPrefix(first.name):''; let html=`<div class="page-head"><span>${escapeHTML(head)}</span><span>الجزء ${first?arabicDigits(first.jozz):'—'}</span></div>`;
  let last=''; let inner=''; let currentLine=null;
  for(const a of rows){
    const n=stripPrefix(a.name);
    if(n!==last){inner+=`<div class="surah-banner">سُورَةُ ${escapeHTML(n)}</div>`;if(a.aya_no===1&&a.sora!==1&&a.sora!==9)inner+=`<div class="bismillah">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</div>`;last=n; currentLine=null;}
    const line=Number(a.line_start||0);
    if(line && line!==currentLine){if(currentLine!==null)inner+='</div>';inner+=`<div class="quran-line" data-line="${line}">`;currentLine=line;}
    inner+=makeAyahHTML(a);
  }
  if(currentLine!==null)inner+='</div>';
  html+=`<div class="page-text">${inner}</div><div class="page-number">${arabicDigits(p)}</div>`;el.innerHTML=html;
  if(isCurrent)bindAyahs(el);
}
function bindAyahs(root){$$('.ayah',root).forEach(el=>el.addEventListener('click',()=>{const a=state.book.ayahById.get(Number(el.dataset.id));if(a)openAyah(a)}))}
function openAyah(a){state.selectedAyah=a;$('#ayahHeading').textContent=`${stripPrefix(a.name)} — الآية ${arabicDigits(a.aya_no)}`;$('#ayahQuote').textContent=a.aya_text;$('#ayahDetails').innerHTML='<div class="muted">جارِ تحميل التفسير عند الطلب…</div>';openModal('#ayahSheet')}
async function loadAyahTafsir(){if(!state.selectedAyah)return;try{const books=await fetchTafsirBooks(state.selectedAyah.sora);const book=books[0];if(!book){$('#ayahDetails').textContent='لا تتوفر كتب تفسير لهذه الآية حاليًا.';return}const data=await fetchTafsir(state.selectedAyah.sora,state.selectedAyah.aya_no,book.id);$('#ayahDetails').innerHTML=`<strong>${escapeHTML(book.name)}</strong><p>${escapeHTML((data.content||[]).map(x=>x.text).join('\n'))}</p>`}catch(e){$('#ayahDetails').textContent='تعذر تحميل التفسير الآن.'}}
function renderSurahSelects(){const opts=state.book.surahs.map(s=>`<option value="${s.id}">${arabicDigits(s.id)} — ${escapeHTML(stripPrefix(s.name))}</option>`).join('');$('#audioSurahSelect').innerHTML=opts;$('#audioSurahSelect').value=state.book.pages.get(state.page)?.[0]?.sora||1}
function renderReciters(){const list=recitationsForRiwayah(state.reciters,state.riwayah);state.filteredReciters=list;$('#reciterSelect').innerHTML='<option value="">اختر القارئ</option>'+list.map((r,i)=>`<option value="${i}">${escapeHTML(r.name)} — ${escapeHTML(r.nameMoshaf)}</option>`).join('');$('#reciterDownloads').innerHTML=list.slice(0,80).map((r,i)=>`<div class="reciter-row"><div><strong>${escapeHTML(r.name)}</strong><small>${escapeHTML(r.nameMoshaf)}</small></div><button class="outline-btn" data-dl="${i}">تحميل</button></div>`).join('');
}
function chooseReciter(index){state.audioRec=state.filteredReciters[Number(index)];if(state.audioRec)$('#dockReciter').textContent=state.audioRec.name}
function playCurrent(){if(!state.audioRec){const candidates=state.filteredReciters;state.audioRec=candidates[0];if(!state.audioRec){toast('لا يوجد قارئ متاح لهذه الرواية الآن');return}$('#dockReciter').textContent=state.audioRec.name} const sur=state.book.pages.get(state.page)?.[0]?.sora||1;audio.src=audioUrl(state.audioRec,sur);audio.play().then(()=>{$('#playBtn').textContent='❚❚'}).catch(()=>toast('اضغط تشغيل مرة أخرى للسماح بالصوت'))}
function togglePlay(){if(audio.paused)playCurrent();else audio.pause()}
audio.addEventListener('pause',()=>$('#playBtn').textContent='▶');audio.addEventListener('play',()=>$('#playBtn').textContent='❚❚');audio.addEventListener('timeupdate',()=>{$('#miniProgressFill').style.width=audio.duration?`${audio.currentTime/audio.duration*100}%`:'0%'});audio.addEventListener('ended',()=>{if($('#finishMode').value==='continue')renderPage(state.page+1);else if($('#finishMode').value==='repeat'){audio.currentTime=0;audio.play().catch(()=>{})}});

function swipeSetup(){let start=null;$('#reader').addEventListener('touchstart',e=>{if(!$('#touchToggle').checked)return;start=e.touches[0].clientX},{passive:true});$('#reader').addEventListener('touchend',e=>{if(start===null)return;const dx=e.changedTouches[0].clientX-start;if(Math.abs(dx)>55){renderPage(state.page+(dx<0?1:-1));}start=null},{passive:true});}
function setupEvents(){
  $('#menuBtn').onclick=()=>{renderSide('surahs');openModal('#sidePanel')};$('#searchBtn').onclick=()=>{openModal('#searchModal');$('#globalSearch').focus()};$('#settingsBtn').onclick=()=>openModal('#settingsModal');$('#immersiveBtn').onclick=()=>immersiveToggle();$('#playBtn').onclick=togglePlay;$('#audioExpand').onclick=()=>{renderReciters();openModal('#readerModal')};
  $$('.close').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
  $$('.page-overlay').forEach(b=>b.onclick=()=>renderPage(state.page+(b.dataset.dir==='next'?1:-1)));
  $('#reader').addEventListener('click',e=>{if(e.target.closest('.ayah'))return;if(e.target.closest('.page-overlay'))return;immersiveToggle()});
  window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')renderPage(state.page+1);if(e.key==='ArrowRight')renderPage(state.page-1);if(e.key==='Escape'){closeModal('#sidePanel');closeModal('#searchModal');closeModal('#settingsModal');closeModal('#readerModal');closeModal('#ayahSheet')}});
  $('#riwayahSelect').onchange=async e=>{state.riwayah=e.target.value;save('riwayah',state.riwayah);await loadQuran();renderReciters()};
  $('#fontRange').oninput=e=>{state.fontSize=Number(e.target.value);applySettings()};$('#themeSelect').onchange=e=>{state.theme=e.target.value;applySettings()};
  $('#wakeToggle').onchange=async e=>{if(e.target.checked){try{await document.documentElement.requestFullscreen?.()}catch{} try{state.wake=await navigator.wakeLock?.request('screen')}catch{}}else{try{await state.wake?.release()}catch{}}};
  $$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  $$('.tab').forEach(b=>b.onclick=()=>{ $$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSide(b.dataset.side)});
  $('#audioSurahSelect').onchange=e=>{const s=Number(e.target.value);const row=state.book.surahs.find(x=>x.id===s);if(row)renderPage(row.page)};$('#reciterSelect').onchange=e=>chooseReciter(e.target.value);
  $$('.ayah-actions button').forEach(b=>b.onclick=()=>ayahAction(b.dataset.ayah));
  $('#globalSearch').oninput=debounce(runSearch,450); $$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.searchType=b.dataset.searchType;runSearch()});
  $$('[data-dl]').forEach(()=>{});
  $('#clearCacheBtn').onclick=async()=>{await Store.clearStore('audio');toast('تم مسح التخزين الصوتي المحلي')}; $('#accountBtn').onclick=()=>{renderAccount();openModal('#accountModal')};
  $('#createPlaylistBtn').onclick=createPlaylist;
  swipeSetup();
}
function renderSide(kind){const box=$('#sideContent');if(kind==='surahs'){box.innerHTML=state.book.surahs.map(s=>`<div class="list-item" data-page="${s.page}"><strong>${escapeHTML(stripPrefix(s.name))}</strong><small>الجزء ${arabicDigits(s.juz)} · ص ${arabicDigits(s.page)}</small></div>`).join('');$$('.list-item',box).forEach(x=>x.onclick=()=>{renderPage(Number(x.dataset.page));closeModal('#sidePanel')})}else if(kind==='juz'){const js=juzStartPages(state.book.rows);box.innerHTML=js.map((x,i)=>`<div class="list-item" data-page="${x?.page||1}"><strong>الجزء ${arabicDigits(i+1)}</strong><small>اضغط للانتقال إلى بداية الجزء · الأرباع تُستكمل من فهرس المصحف</small></div>`).join('');$$('.list-item',box).forEach(x=>x.onclick=()=>{renderPage(Number(x.dataset.page));closeModal('#sidePanel')})}else if(kind==='notes'){box.innerHTML=state.notes.length?state.notes.map(n=>`<div class="list-item"><strong>${escapeHTML(n.text)}</strong><small>ص ${arabicDigits(n.page||1)}</small></div>`).join(''):'<div class="empty">لا توجد ملاحظات بعد.</div>'}else{box.innerHTML=state.bookmarks.length?state.bookmarks.map(n=>`<div class="list-item" data-page="${n.page}"><strong>${escapeHTML(n.title||'مرجعية')}</strong><small>ص ${arabicDigits(n.page)}</small></div>`).join(''):'<div class="empty">لا توجد مرجعيات بعد.</div>';$$('.list-item',box).forEach(x=>x.onclick=()=>{renderPage(Number(x.dataset.page));closeModal('#sidePanel')})}}
async function ayahAction(action){const a=state.selectedAyah;if(!a)return;switch(action){case'copy':await navigator.clipboard?.writeText(a.aya_text);toast('تم نسخ الآية');break;case'share':if(navigator.share)navigator.share({title:`${stripPrefix(a.name)} — ${a.aya_no}`,text:a.aya_text});else{await navigator.clipboard?.writeText(a.aya_text);toast('تم نسخ الآية للمشاركة')}break;case'tafsir':await loadAyahTafsir();break;case'bookmark':state.bookmarks.unshift({page:a.page,title:`${stripPrefix(a.name)} — ${a.aya_no}`,createdAt:Date.now()});saveLocalLists();toast('تمت إضافة المرجعية');break;case'note':{const text=prompt('اكتب الملاحظة');if(text){state.notes.unshift({page:a.page,text,createdAt:Date.now()});saveLocalLists();toast('تم حفظ الملاحظة')}}break;case'repeat':$('#repeatAyahToggle').checked=true;openModal('#readerModal');toast('فعّل التكرار واختر عدد المرات');break;case'image':generateAyahImage(false);break;case'image-tafsir':generateAyahImage(true);break}}
async function generateAyahImage(withTafsir){const a=state.selectedAyah;const c=document.createElement('canvas');c.width=1200;c.height=withTafsir?850:650;const x=c.getContext('2d');x.fillStyle='#ead9b8';x.fillRect(0,0,c.width,c.height);x.fillStyle='#2c1b0f';x.textAlign='center';x.font='54px Hafs';wrapCanvas(x,a.aya_text,1100,180,88);x.font='22px Tahoma';x.fillStyle='#6e5534';x.fillText(`سورة ${stripPrefix(a.name)} — الآية ${a.aya_no}`,600,590);if(withTafsir){try{const books=await fetchTafsirBooks(a.sora);const d=await fetchTafsir(a.sora,a.aya_no,books[0]?.id||1);x.font='22px Tahoma';x.fillStyle='#3d2b19';wrapCanvas(x,(d.content||[]).map(z=>z.text).join(' '),1100,350,34)}catch{}}const url=c.toDataURL('image/png');const ael=document.createElement('a');ael.href=url;ael.download='samee3-ayah.png';ael.click()}
function wrapCanvas(ctx,text,maxWidth,startY,lineH){const words=String(text).split(' ');let line='';let y=startY;for(const w of words){const test=line?`${line} ${w}`:w;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,600,y);line=w;y+=lineH}else line=test}if(line)ctx.fillText(line,600,y)}
function createPlaylist(){const name=$('#playlistName').value.trim();if(!name)return;state.playlists.push({id:crypto.randomUUID(),name});saveLocalLists();renderPlaylists();$('#playlistName').value='';toast('تم إنشاء قائمة التشغيل')}
function renderPlaylists(){$('#playlistRow').innerHTML=state.playlists.map(p=>`<span class="playlist-chip">${escapeHTML(p.name)}</span>`).join('')}
async function runSearch(){const q=$('#globalSearch').value.trim();const out=$('#searchResults');if(!q){out.innerHTML='<div class="empty">اكتب كلمة البحث.</div>';return}out.innerHTML='<div class="empty">جاري البحث…</div>';try{if(['all','quran'].includes(state.searchType)){const res=searchRows(state.book.rows,q);if(res.length)out.innerHTML=res.slice(0,30).map(a=>`<div class="list-item" data-page="${a.page}"><strong>${escapeHTML(a.aya_text)}</strong><small>سورة ${escapeHTML(stripPrefix(a.name))} · آية ${arabicDigits(a.aya_no)}</small></div>`).join('');}if(['all','tafsir','topics','reciters'].includes(state.searchType)){const qp=await searchQuranpedia(q,state.searchType==='tafsir'?'books':state.searchType==='topics'?'topics':state.searchType==='reciters'?'recitations':'');const items=(qp.items||qp.books?.items||qp.topics?.items||qp.reciters?.items||[]);out.innerHTML+=(items.slice(0,20).map(i=>`<div class="list-item"><strong>${escapeHTML(i.name||i.book_info?.name||i.title||i.ar_title||'نتيجة')}</strong><small>${escapeHTML(i.highlighted_text||i.author||'Quranpedia')}</small></div>`).join('')||'<div class="empty">لا توجد نتائج.</div>');}if(state.searchType==='notes'){const xs=state.notes.filter(n=>String(n.text).includes(q));out.innerHTML=xs.length?xs.map(n=>`<div class="list-item"><strong>${escapeHTML(n.text)}</strong><small>ص ${arabicDigits(n.page)}</small></div>`).join(''):'<div class="empty">لا توجد نتائج.</div>'}$$('.list-item',out).forEach(x=>x.onclick=()=>{const p=x.dataset.page;if(p){renderPage(Number(p));closeModal('#searchModal')}})}catch(e){out.innerHTML='<div class="empty">تعذر تنفيذ البحث الآن.</div>'}}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
function switchView(view){state.currentView=view;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='mushaf'){$('#contentView').classList.remove('open');return}$('#contentView').classList.add('open');renderModule(view)}
async function renderModule(view){const c=$('#contentView');if(view==='tools'){c.innerHTML=`<div class="view-grid"><div class="hero-module"><h2>أدوات المسلم</h2><p>الصلاة، الأذكار، الختمة، والإحصائيات في مكان واحد.</p></div><div class="module-card"><h3>مواقيت الصلاة</h3><div id="prayerModule">جاري الحساب…</div></div><div class="module-card"><h3>الأذكار</h3><p>أذكار الصباح والمساء والنوم وأذكار ما بعد الصلاة.</p><button class="gold-btn" id="openAzkar">فتح الأذكار</button></div><div class="module-card"><h3>الإحصائيات</h3><div>الصفحة الحالية: ${arabicDigits(state.page)}</div><div>الرواية: ${escapeHTML(RIWAYAT[state.riwayah].label)}</div></div></div>`;$('#openAzkar').onclick=()=>toast('سيتم فتح مكتبة الأذكار من المصدر عند اختيار القسم');setupPrayer(true)}else if(view==='audio'){c.innerHTML=`<div class="view-grid"><div class="hero-module"><h2>المكتبة السمعية</h2><p>قرّاء وتلاوات من MP3Quran، مصنفة حسب الرواية.</p></div><div class="module-card" style="grid-column:1/-1"><div class="search-box"><input id="audioSearch" placeholder="ابحث عن قارئ…" /></div><div id="audioLibrary"></div></div></div>`;renderAudioLibrary();$('#audioSearch').oninput=()=>renderAudioLibrary($('#audioSearch').value)}else if(view==='library'){c.innerHTML=`<div class="view-grid"><div class="hero-module"><h2>المكتبة القرآنية والإسلامية</h2><p>التفسير، الترجمات، والحديث مع تحميل تدريجي.</p></div><div class="module-card"><h3>كتب التفسير</h3><button class="gold-btn" id="loadTafsirBooks">عرض الكتب</button><div id="tafsirBooksBox"></div></div><div class="module-card"><h3>الترجمات</h3><button class="gold-btn" id="loadTranslations">عرض الترجمات</button><div id="translationsBox"></div></div><div class="module-card" style="grid-column:1/-1"><h3>كتب الحديث</h3><div class="book-list">${HADITH_BOOKS.map(b=>`<button class="outline-btn hadith-book" data-slug="${b.slug}">${escapeHTML(b.name)} ${b.status==='requires-source'?'— يحتاج موصل مصدر مناسب':''}</button>`).join('')}</div><div id="hadithBox"></div></div></div>`;$('#loadTafsirBooks').onclick=async()=>{$('#tafsirBooksBox').innerHTML='<p class="muted">جاري التحميل…</p>';try{const bs=await fetchTafsirBooks(1);$('#tafsirBooksBox').innerHTML=bs.slice(0,20).map(b=>`<span class="tag">${escapeHTML(b.name)}</span>`).join('')}catch{$('#tafsirBooksBox').innerHTML='<p class="muted">تعذر التحميل.</p>'}};$('#loadTranslations').onclick=async()=>{$('#translationsBox').innerHTML='<p class="muted">جاري التحميل…</p>';try{const ts=await fetchTranslations();$('#translationsBox').innerHTML=ts.slice(0,60).map(t=>`<span class="tag">${escapeHTML(t.title||t.key||'ترجمة')}</span>`).join('')}catch{$('#translationsBox').innerHTML='<p class="muted">تعذر التحميل.</p>'}};$$('.hadith-book').forEach(b=>b.onclick=()=>loadHadith(b.dataset.slug))}}
async function renderAudioLibrary(q=''){const out=$('#audioLibrary');let list=recitationsForRiwayah(state.reciters,state.riwayah);if(q)list=list.filter(r=>r.name.includes(q)||r.nameMoshaf.includes(q));out.innerHTML=list.slice(0,120).map((r,i)=>`<div class="reciter-row"><div><strong>${escapeHTML(r.name)}</strong><small>${escapeHTML(r.nameMoshaf)} · ${escapeHTML(r.type)}</small></div><button class="outline-btn" data-play-audio="${state.reciters.indexOf(r)}">تشغيل</button></div>`).join('');$$('[data-play-audio]').forEach(b=>b.onclick=()=>{chooseReciter(b.dataset.playAudio);switchView('mushaf');playCurrent()})}
async function loadHadith(slug){const box=$('#hadithBox');box.innerHTML='<div class="empty">جاري تحميل الكتاب…</div>';try{const data=await fetchHadithEdition(slug);const had=(data.hadiths||[]).slice(0,120);box.innerHTML=had.map(h=>`<div class="hadith-card"><div><strong>${escapeHTML(h.hadithnumber||'')}</strong></div><div>${escapeHTML(h.text||'')}</div></div>`).join('')||'<div class="empty">الكتاب فارغ.</div>'}catch(e){box.innerHTML='<div class="empty">هذا الكتاب غير متاح عبر موصل البيانات المفتوح المستخدم حاليًا. لن يتم عرض بيانات غير موثقة بدلًا منه.</div>'}}
function setupPrayer(module=false){if(!navigator.geolocation){if(module)$('#prayerModule').textContent='الموقع غير متاح';return}navigator.geolocation.getCurrentPosition(async pos=>{try{const d=await getPrayerTimes(pos.coords.latitude,pos.coords.longitude);const np=nextPrayer(d.data.timings);const label=`${np.name} · ${formatCountdown(np)}`;$('#prayerPill').textContent=label;if(module)$('#prayerModule').textContent=label;startCountdown(d.data.timings)}catch{if(module)$('#prayerModule').textContent='تعذر حساب المواقيت'}},()=>{if(module)$('#prayerModule').textContent='اسمح بالموقع لحساب المواقيت'});}function formatCountdown(np){return np?`${arabicDigits(String(Math.max(0,np.minutes-(new Date().getHours()*60+new Date().getMinutes()))))} دقيقة تقريبًا`:''}function startCountdown(t){setInterval(()=>{const n=nextPrayer(t);$('#prayerPill').textContent=`${n.name} · ${formatCountdown(n)}`},30000)}
function renderAccount(){const box=$('#accountContent');if(state.user){box.innerHTML=`<div class="module-card"><h3>أنت مسجل الدخول</h3><p>${escapeHTML(state.user.email||'')}</p><p class="muted">${state.admin?'حساب مدير':'حساب مستخدم'}</p><button class="gold-btn" id="logoutBtn">تسجيل الخروج</button></div>`;$('#logoutBtn').onclick=()=>firebaseApi.signOut(auth).then(()=>{toast('تم تسجيل الخروج');closeModal('#accountModal')});return}box.innerHTML=`<div class="settings-layout"><div class="settings-group"><h3>تسجيل الدخول</h3><label>البريد الإلكتروني<input id="loginEmail" type="email"></label><label>كلمة المرور<input id="loginPassword" type="password"></label><button class="gold-btn" id="loginBtn">دخول</button><button class="outline-btn" id="resetBtn">استعادة كلمة المرور</button></div><div class="settings-group"><h3>إنشاء حساب</h3><label>البريد الإلكتروني<input id="signupEmail" type="email"></label><label>كلمة المرور<input id="signupPassword" type="password" minlength="6"></label><button class="gold-btn" id="signupBtn">إنشاء حساب</button></div></div>`;$('#loginBtn').onclick=async()=>{try{await firebaseApi.signInWithEmailAndPassword(auth,$('#loginEmail').value,$('#loginPassword').value);toast('تم تسجيل الدخول');renderAccount()}catch{toast('تعذر تسجيل الدخول')}};$('#signupBtn').onclick=async()=>{try{const c=await firebaseApi.createUserWithEmailAndPassword(auth,$('#signupEmail').value,$('#signupPassword').value);await ensureUserProfile(c.user);toast('تم إنشاء الحساب');renderAccount()}catch{toast('تعذر إنشاء الحساب')}};$('#resetBtn').onclick=async()=>{try{await firebaseApi.sendPasswordResetEmail(auth,$('#loginEmail').value);toast('تم إرسال رابط الاستعادة')}catch{toast('اكتب بريدك أولًا')}}}
async function adminActions(){if(!state.admin)return;const c=$('#contentView');c.innerHTML=`<div class="view-grid"><div class="hero-module"><h2>لوحة الإدارة</h2><p>تظهر لأن حساب Firebase الحالي موجود في admins وفعّال.</p></div><div class="module-card"><h3>إعدادات المنصة</h3><label>اسم التطبيق<input id="adminAppName" value="مصحف سميع"></label><button class="gold-btn" id="saveAppSettings">حفظ الإعدادات</button></div><div class="module-card"><h3>الإعلانات</h3><textarea id="adminAnnouncement" rows="4" style="width:100%;padding:10px;border-radius:10px;border:1px solid #ddd"></textarea><button class="gold-btn" id="saveAnnouncement">نشر</button></div></div>`;$('#saveAppSettings').onclick=async()=>{try{await firebaseApi.setDoc(firebaseApi.doc(db,'appSettings','main'),{name:$('#adminAppName').value,updatedAt:firebaseApi.serverTimestamp()},{merge:true});toast('تم حفظ إعدادات المنصة')}catch{toast('تعذر الحفظ')}};$('#saveAnnouncement').onclick=async()=>{try{await firebaseApi.addDoc(firebaseApi.collection(db,'announcements'),{text:$('#adminAnnouncement').value,active:true,createdAt:firebaseApi.serverTimestamp()});toast('تم نشر الإعلان')}catch{toast('تعذر النشر')}}}
function setupAuth(){firebaseApi.onAuthStateChanged(auth,async user=>{state.user=user; state.admin=false; if(user){await ensureUserProfile(user);state.admin=await isAdmin(user.uid);try{state.notes=await cloudLoadList(user.uid,'notes');state.bookmarks=await cloudLoadList(user.uid,'bookmarks');state.playlists=await cloudLoadList(user.uid,'playlists')}catch{}} if($('#accountContent')) renderAccount();});}
async function restoreLists(){try{const n=JSON.parse(localStorage.getItem('samee3:notes')||'[]');const b=JSON.parse(localStorage.getItem('samee3:bookmarks')||'[]');const p=JSON.parse(localStorage.getItem('samee3:playlists')||'[]');if(n.length)state.notes=n;if(b.length)state.bookmarks=b;if(p.length)state.playlists=p;renderPlaylists()}catch{}}
function saveLocalLists(){localStorage.setItem('samee3:notes',JSON.stringify(state.notes));localStorage.setItem('samee3:bookmarks',JSON.stringify(state.bookmarks));localStorage.setItem('samee3:playlists',JSON.stringify(state.playlists));if(state.user){Promise.all(state.notes.slice(0,3).map(n=>cloudSaveList(state.user.uid,'notes',n).catch(()=>{})));Promise.all(state.bookmarks.slice(0,3).map(n=>cloudSaveList(state.user.uid,'bookmarks',n).catch(()=>{})));}}
function escapeHTML(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
bootstrap().catch(e=>{console.error(e);toast('تعذر تشغيل المصحف. راجع اتصال البيانات المحلية.')});
