import { auth, db } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/12.9.0/firebase-auth.js';
import { doc, getDoc, setDoc, updateDoc, deleteDoc, collection, getDocs, serverTimestamp, query, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.9.0/firebase-firestore.js';

const API={
  mp3:'https://www.mp3quran.net/api/v3',
  qpedia:'https://api.quranpedia.net/v1',
  qenc:'https://quranenc.com/api/v1',
  hadith:'https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1',
  prayer:'https://api.aladhan.com/v1',
  svg:'https://raw.githubusercontent.com/quran-ws/quran-svg/main/mushafs'
};
const RIWAYAT={
  hafs:{label:'حفص عن عاصم',quranSvg:'hafs',local:'hafs.json'},
  warsh:{label:'ورش عن نافع',quranSvg:'warsh',local:'warsh.json'},
  qaloon:{label:'قالون عن نافع',quranSvg:'qalon',local:'qaloon.json'},
  doori:{label:'الدوري عن أبي عمرو',quranSvg:'douri',local:'doori.json'},
  shouba:{label:'شعبة عن عاصم',quranSvg:'shubah',local:'shouba.json'},
  soosi:{label:'السوسي عن أبي عمرو',quranSvg:null,local:'soosi.json'}
};
const SURA_NAMES=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const state={page:+localStorage.getItem('s3_page')||1,riwayah:localStorage.getItem('s3_riwayah')||'hafs',theme:localStorage.getItem('s3_theme')||'sepia',fontSize:+localStorage.getItem('s3_font')||18,immersive:false,drawer:false,notes:JSON.parse(localStorage.getItem('s3_notes')||'[]'),bookmarks:JSON.parse(localStorage.getItem('s3_marks')||'[]'),playlists:JSON.parse(localStorage.getItem('s3_playlists')||'{"الرخص الشرعية":[],"الورد الليلي":[],"ورد الجمعة":[]}'),reciters:[],timings:[],timingRead:null,audio:null,currentAyah:null,user:null,admin:false,prayer:null,swipeStartX:null,settings:{language:'ar',keepAwake:false,showClock:true,sideTouch:true,autoHighlight:true,autoNextPage:true}};
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page3=n=>String(n).padStart(3,'0');
const cleanName=s=>String(s||'').replace(/[ًٌٍَُِّْٰ]/g,'').trim();
const saveLocal=()=>{localStorage.setItem('s3_page',state.page);localStorage.setItem('s3_riwayah',state.riwayah);localStorage.setItem('s3_theme',state.theme);localStorage.setItem('s3_font',state.fontSize);localStorage.setItem('s3_notes',JSON.stringify(state.notes));localStorage.setItem('s3_marks',JSON.stringify(state.bookmarks));localStorage.setItem('s3_playlists',JSON.stringify(state.playlists));};
async function getJSON(url,opts={}){const res=await fetch(url,{...opts,headers:{Accept:'application/json',...(opts.headers||{})}});if(!res.ok)throw new Error(`${res.status} ${url}`);return res.json()}
async function getText(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status}`);return r.text()}

function layout(){
app.innerHTML=`<div class="app ${state.theme}" id="root">
<header class="topbar" id="topbar">
  <button class="icon gold" data-action="menu" title="القائمة">☰</button>
  <div class="brand"><img src="./icons/samee3-logo.png" alt="مصحف سميع"><div><strong>مصحف سميع</strong><span>Qur'an & Study</span></div></div>
  <div class="top-center"><div id="pageMeta">المصحف</div><div id="prayerCountdown">الصلاة القادمة — جاري الحساب</div></div>
  <div class="top-actions"><button class="icon" data-action="search">⌕</button><button class="icon" data-action="settings">⚙</button><button class="icon" data-action="account">◉</button></div>
</header>
<main>
<section id="reader" class="reader-wrap">
  <div class="immersive-hint" id="immersiveHint">المس منتصف الشاشة لإظهار الأدوات</div>
  <div id="mushafBook" class="mushaf-book"></div>
  <div class="page-nav"><button class="round" data-action="prev">‹</button><div id="pageNumber">1</div><button class="round" data-action="next">›</button></div>
</section>
<section id="module" class="module" hidden></section>
</main>
<footer class="player" id="player"><button class="player-more" data-action="player">⌃</button><div class="player-track"><strong id="trackSurah">الفاتحة</strong><small id="trackReciter">اختر القارئ</small></div><button class="play" data-action="play">▶</button><div class="progress"><input id="audioSeek" type="range" min="0" max="100" value="0"></div><button class="icon" data-action="playlist">≡</button></footer>
<audio id="audio" preload="metadata"></audio>
<div id="overlay"></div><div id="drawer"></div><div id="sheet"></div><div id="toast"></div>
</div>`;
}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function applyTheme(){document.getElementById('root').className=`app ${state.theme}`;document.documentElement.style.setProperty('--qfont',`${state.fontSize}px`);}

async function loadLocalRiwayah(){
  const key=state.riwayah; const u=`./data/riwayat/${RIWAYAT[key].local}`;
  const data=await getJSON(u); window.__riwayahData=data.map(x=>({...x,page:Number(x.page??1),sura:Number(x.sura??x.sura_no??x.sora??1),ayah:Number(x.aya_no??x.ayah??1)}));
  return window.__riwayahData;
}
function pageRows(page){return (window.__riwayahData||[]).filter(x=>Number(x.page)===page)}
function svgUrl(page){const slug=RIWAYAT[state.riwayah].quranSvg;if(!slug)return null;return `${API.svg}/${slug}/kfqc/svg/${page3(page)}.svg`}
function svgJsonUrl(page){const slug=RIWAYAT[state.riwayah].quranSvg;if(!slug)return null;return `${API.svg}/${slug}/kfqc/json/${page3(page)}.json`}
async function renderPage(page){
 const box=document.createElement('article');box.className='page';box.dataset.page=page;
 const src=svgUrl(page);
 if(src){
   try{
     const svg=await getText(src); box.innerHTML=`<div class="page-art" id="art-${page}">${svg}</div><div class="page-overlay" aria-hidden="true"></div><div class="page-no">${page}</div>`;
     box.querySelectorAll('.page-art .ayahPolygon').forEach(path=>{path.style.pointerEvents='auto';path.style.fill='transparent';path.addEventListener('click',ev=>{ev.stopPropagation();openAyah(Number(path.getAttribute('surah')),Number(path.getAttribute('ayah')),page)})});
     box.querySelectorAll('.page-art path:not(.ayahPolygon),.page-art g').forEach(el=>{el.style.pointerEvents='none'});
     return box;
   }catch{}
 }
 const rows=pageRows(page);box.innerHTML=`<div class="fallback-page"><div class="fallback-header"><span>${esc(cleanName(rows[0]?.sura_name_ar||SURA_NAMES[(rows[0]?.sura||1)-1]))}</span><span>الجزء ${rows[0]?.jozz||1}</span></div><div class="fallback-text" style="font-size:${state.fontSize}px">${rows.map(r=>`<span class="fallback-ayah" data-s="${r.sura}" data-a="${r.ayah}" data-p="${page}">${esc(r.aya_text||r.text||'')}</span>`).join(' ')}</div><div class="page-no">${page}</div></div>`;
 box.querySelectorAll('.fallback-ayah').forEach(el=>el.onclick=()=>openAyah(+el.dataset.s,+el.dataset.a,+el.dataset.p));return box;
}
async function renderPages(){
  const book=document.getElementById('mushafBook');book.innerHTML='<div class="loader-page">جاري تجهيز صفحة المصحف…</div>';
  try{await loadLocalRiwayah();}catch(e){book.innerHTML=`<div class="error-card">تعذر تحميل بيانات الرواية المحلية.<br><button data-action="retry">إعادة المحاولة</button></div>`;return}
  state.page=Math.min(604,Math.max(1,state.page));saveLocal();
  const isDesktop=window.innerWidth>=900; const pages=isDesktop?[state.page,state.page===1?2:state.page-1]:[state.page];
  const uniq=[...new Set(pages)].filter(p=>p>=1&&p<=604).sort((a,b)=>isDesktop?a-b:b-a);
  const nodes=await Promise.all(uniq.map(renderPage)); book.innerHTML='';nodes.forEach(n=>book.appendChild(n));
  document.getElementById('pageNumber').textContent=state.page; updateMeta(); applyActiveAyah();
}
function updateMeta(){const rows=pageRows(state.page);const first=rows[0];const name=cleanName(first?.sura_name_ar||SURA_NAMES[(first?.sura||1)-1]||'المصحف');const juz=first?.jozz||Math.ceil(state.page/20);document.getElementById('pageMeta').innerHTML=`<b>${esc(name)}</b><span>الجزء ${juz}</span><span>الحزب ${(Math.ceil(state.page/10))}</span>`;document.getElementById('pageNumber').textContent=state.page;}
function goPage(p){state.page=Math.max(1,Math.min(604,p));saveLocal();renderPages();}
function prevPage(){goPage(state.page-1)}function nextPage(){goPage(state.page+1)}

function applyActiveAyah(){document.querySelectorAll('.ayahPolygon.active').forEach(e=>e.classList.remove('active'));document.querySelectorAll('.fallback-ayah.active').forEach(e=>e.classList.remove('active'));if(!state.currentAyah)return;const [s,a]=state.currentAyah;document.querySelectorAll(`.ayahPolygon[surah="${s}"][ayah="${a}"], .fallback-ayah[data-s="${s}"][data-a="${a}"]`).forEach(e=>e.classList.add('active'))}
async function openAyah(surah,ayah,page){
 state.currentAyah=[surah,ayah];applyActiveAyah();
 const sheet=document.getElementById('sheet');
 sheet.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card"><div class="handle"></div><div class="sheet-head"><div><b>سورة ${esc(SURA_NAMES[surah-1])}</b><small>آية ${ayah} • صفحة ${page}</small></div><button class="icon" data-action="closeSheet">✕</button></div><div class="ayah-text-big" id="ayahLiveText">جاري تحميل الآية…</div><div class="ayah-actions"><button data-action="copyAyah">نسخ</button><button data-action="shareAyah">مشاركة</button><button data-action="markAyah">مرجعية</button><button data-action="noteAyah">ملاحظة</button><button data-action="playAyah">استماع</button><button data-action="repeatAyah">تكرار</button><button data-action="imageAyah">صورة</button><button data-action="tafseerAyah">التفسير</button></div><div id="ayahExtra"></div></section>`;sheet.classList.add('open');
 try{const data=await getJSON(`${API.qpedia}/mushafs/1/${surah}/${ayah}`);document.getElementById('ayahLiveText').textContent=data.text||pageRows(page).find(r=>r.sura===surah&&r.ayah===ayah)?.aya_text||'';sheet.dataset.ayahText=data.text||'';}catch{const r=pageRows(page).find(x=>x.sura===surah&&x.ayah===ayah);document.getElementById('ayahLiveText').textContent=(r?.aya_text||'').replace(/\s*[٠-٩0-9]+$/,'');}
}
function closeSheet(){document.getElementById('sheet').classList.remove('open')}
async function copyAyah(){const text=document.getElementById('ayahLiveText').textContent;await navigator.clipboard?.writeText(text);showToast('تم نسخ الآية')}
async function shareAyah(){const text=document.getElementById('ayahLiveText').textContent;if(navigator.share)await navigator.share({title:'مصحف سميع',text});else {await navigator.clipboard?.writeText(text);showToast('تم نسخ الآية للمشاركة')}}
function markAyah(){const k=`${state.riwayah}:${state.currentAyah?.[0]}:${state.currentAyah?.[1]}`;if(!state.bookmarks.some(x=>x.key===k))state.bookmarks.unshift({key:k,surah:state.currentAyah[0],ayah:state.currentAyah[1],page:state.page,date:Date.now()});saveLocal();syncUserState();showToast('تمت إضافة المرجعية')}
function noteAyah(){const note=prompt('اكتب ملاحظتك');if(!note)return;state.notes.unshift({id:crypto.randomUUID(),text:note,surah:state.currentAyah[0],ayah:state.currentAyah[1],page:state.page,date:Date.now()});saveLocal();syncUserState();showToast('تم حفظ الملاحظة')}
function openEmbed(type='tafsir'){const [s,a]=state.currentAyah||[1,1];const extra=document.getElementById('ayahExtra');extra.innerHTML=`<div class="embed-wrap"><iframe title="الموسوعة القرآنية" src="https://quranpedia.net/embed?surah=${s}&ayah=${a}&type=${type}&theme=sepia" loading="lazy"></iframe></div>`}
function imageAyah(){const text=document.getElementById('ayahLiveText').textContent;const c=document.createElement('canvas');c.width=1200;c.height=700;const ctx=c.getContext('2d');ctx.fillStyle='#f7efd8';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#b79655';ctx.lineWidth=8;ctx.strokeRect(28,28,c.width-56,c.height-56);ctx.fillStyle='#3b2a16';ctx.font='42px serif';ctx.textAlign='center';ctx.direction='rtl';wrapCanvas(ctx,text,600,300,1000,68);ctx.font='24px serif';ctx.fillStyle='#8b713d';ctx.fillText('مصحف سميع',600,625);const a=document.createElement('a');a.download=`samee3-${state.currentAyah?.[0]}-${state.currentAyah?.[1]}.png`;a.href=c.toDataURL('image/png');a.click()}
function wrapCanvas(ctx,text,x,y,maxW,lineH){const words=text.split(/\s+/);let line='';const lines=[];for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);const start=y-(lines.length-1)*lineH/2;lines.forEach((l,i)=>ctx.fillText(l,x,start+i*lineH))}
async function repeatAyah(){if(!state.currentAyah)return;const count=Number(prompt('عدد مرات التكرار',3)||3);await ensureAudioForCurrent();if(!state.audio)return;state.audio.repeatCount=count;state.audio.remaining=count;playCurrentAyah()}

async function loadReciters(){try{const d=await getJSON(`${API.mp3}/reciters?language=ar`);state.reciters=[];(d.reciters||[]).forEach(r=>(r.moshaf||[]).forEach(m=>{state.reciters.push({id:r.id,name:r.name,readName:m.name,server:m.server,moshafId:m.id,surahs:(m.surah_list||'').split(',').filter(Boolean).map(Number),moshafType:m.moshaf_type,riwayah:guessRiwayah(m.name),readNameLc:String(m.name).toLowerCase()})}));}catch(e){state.reciters=[]}}
function guessRiwayah(n){const s=String(n||'');if(s.includes('ورش'))return'warsh';if(s.includes('قالون'))return'qaloon';if(s.includes('الدوري'))return'doori';if(s.includes('شعبة'))return'shouba';if(s.includes('السوسي'))return'soosi';return'hafs'}
function filteredReciters(){return state.reciters.filter(r=>r.riwayah===state.riwayah && r.surahs.includes(pageRows(state.page)[0]?.sura||1))}
async function openPlayer(){const sheet=document.getElementById('sheet');await loadReciters();const rec=filteredReciters();sheet.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card large"><div class="handle"></div><div class="sheet-head"><div><b>مشغل التلاوة</b><small>الرواية • القارئ • المقطع</small></div><button class="icon" data-action="closeSheet">✕</button></div><div class="control-grid"><label>الرواية<select id="riwayahPick">${Object.entries(RIWAYAT).map(([k,v])=>`<option value="${k}" ${k===state.riwayah?'selected':''}>${v.label}</option>`).join('')}</select></label><label>القارئ<select id="reciterPick">${rec.map((r,i)=>`<option value="${i}">${esc(r.name)} — ${esc(r.readName)}</option>`).join('')||'<option>لا توجد تلاوة متاحة</option>'}</select></label><label>من سورة<select id="fromSurah">${SURA_NAMES.map((n,i)=>`<option value="${i+1}">${n}</option>`).join('')}</select></label><label>الآية من<input id="fromAyah" type="number" min="1" value="1"></label><label>إلى سورة<select id="toSurah">${SURA_NAMES.map((n,i)=>`<option value="${i+1}">${n}</option>`).join('')}</select></label><label>الآية إلى<input id="toAyah" type="number" min="1" value="7"></label></div><div class="setting-list"><button data-action="toggleHighlight">${state.settings.autoHighlight?'✓':'○'} تظليل وتتبع الآية</button><button data-action="repeatCurrent">تكرار الآية</button><button data-action="repeatSegment">تكرار المقطع</button><button data-action="downloadCurrent">تحميل السورة Offline</button></div><div class="playlist-add"><b>إضافة إلى قائمة تشغيل</b><div>${Object.keys(state.playlists).map(k=>`<button data-playlist="${esc(k)}">${esc(k)}</button>`).join('')}</div></div><div id="downloadStatus" class="mini"></div></section>`;sheet.classList.add('open');bindPlayerSheet(rec)}
function bindPlayerSheet(rec){const rp=document.getElementById('riwayahPick');rp.onchange=async()=>{state.riwayah=rp.value;saveLocal();await renderPages();openPlayer()};document.getElementById('playBtn')?.addEventListener('click',()=>{});document.querySelectorAll('[data-playlist]').forEach(b=>b.onclick=()=>{const r=rec[Number(document.getElementById('reciterPick').value)];if(!r)return;state.playlists[b.dataset.playlist].push({sura:pageRows(state.page)[0]?.sura||1,reciter:r.name,moshaf:r.moshafId,date:Date.now()});saveLocal();syncUserState();showToast('أضيفت إلى قائمة التشغيل')});}
async function ensureAudioForCurrent(){
 const sura=pageRows(state.page)[0]?.sura||1;let r=filteredReciters()[0];const select=document.getElementById('reciterPick');if(select)r=filteredReciters()[Number(select.value)]||r;if(!r)return;state.audio={r,sura};const audio=document.getElementById('audio');audio.src=`${r.server}${page3(sura)}.mp3`;document.getElementById('trackSurah').textContent=SURA_NAMES[sura-1];document.getElementById('trackReciter').textContent=r.name;return audio;
}
async function loadTiming(){if(!state.audio?.r)return;const r=state.audio.r;try{state.timings=await getJSON(`${API.mp3}/ayat_timing?surah=${state.audio.sura}&read=${r.moshafId}`);state.timingRead=r.moshafId}catch{state.timings=[]}}
async function playCurrentAyah(){const audio=await ensureAudioForCurrent();await loadTiming();if(!audio)return;const target=state.currentAyah?.[1];const t=state.timings?.find(x=>Number(x.ayah)===Number(target));if(t){audio.currentTime=Number(t.start_time)/1000}await audio.play().catch(()=>{});}
async function playSura(){const audio=await ensureAudioForCurrent();await loadTiming();await audio?.play().catch(()=>{});}
async function downloadCurrent(){const status=document.getElementById('downloadStatus');const audio=await ensureAudioForCurrent();if(!audio||!state.audio?.r){status.textContent='اختر قارئًا أولًا';return}const url=audio.src;status.textContent='جاري حفظ التلاوة للاستخدام بدون إنترنت…';try{const cache=await caches.open('samee3-audio-v1');const res=await fetch(url,{mode:'cors'});await cache.put(url,res.clone());await idbPut('audio',url,new Blob([await res.arrayBuffer()],{type:res.headers.get('content-type')||'audio/mpeg'}));status.textContent='تم حفظ السورة في هذا الجهاز.'}catch{status.textContent='تعذر الحفظ بسبب إعدادات المصدر/المتصفح. ستظل التلاوة متاحة Online.'}}

async function openSearch(){const sheet=document.getElementById('sheet');sheet.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card large"><div class="handle"></div><div class="sheet-head"><b>البحث الشامل</b><button class="icon" data-action="closeSheet">✕</button></div><input id="universalSearch" class="search-big" placeholder="آية، سورة، تفسير، قارئ، حديث، ملاحظة…" autofocus><div class="search-tabs"><button data-st="all" class="active">الكل</button><button data-st="quran">القرآن</button><button data-st="tafsir">التفسير</button><button data-st="reciters">القراء</button><button data-st="notes">ملاحظاتي</button><button data-st="books">الكتب</button></div><div id="searchResults" class="results"><div class="mini">اكتب كلمة للبحث.</div></div></section>`;sheet.classList.add('open');const input=document.getElementById('universalSearch');let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>runSearch(input.value),350)};}
async function runSearch(q){const box=document.getElementById('searchResults');q=q.trim();if(q.length<2){box.innerHTML='<div class="mini">اكتب كلمتين على الأقل.</div>';return}box.innerHTML='<div class="mini">جاري البحث…</div>';const results=[];const norm=strip(q);for(const r of (window.__riwayahData||[])){if(strip(r.aya_text||'').includes(norm))results.push({type:'quran',title:`${r.sura_name_ar||SURA_NAMES[(r.sura||1)-1]} — آية ${r.ayah||r.aya_no}`,text:r.aya_text,page:Number(r.page),s:r.sura,a:r.ayah||r.aya_no});if(results.length>=20)break}for(const n of state.notes){if(strip(n.text).includes(norm))results.push({type:'notes',title:'ملاحظة شخصية',text:n.text,page:n.page,s:n.surah,a:n.ayah})}try{const r=await getJSON(`${API.qpedia}/search/${encodeURIComponent(q)}`);for(const group of ['books','topics','notes','fatwas'])for(const it of (r[group]?.items||[]).slice(0,5))results.push({type:group,title:it.book_info?.name||it.name||it.title||q,text:it.highlighted_text||it.description||''})}catch{}const names=state.reciters.filter(r=>strip(r.name).includes(norm)||strip(r.readName).includes(norm)).slice(0,8);names.forEach(r=>results.push({type:'reciters',title:r.name,text:r.readName}));box.innerHTML=results.slice(0,40).map((r,i)=>`<button class="result-row" data-res="${i}"><span class="type">${esc(r.type)}</span><strong>${esc(r.title)}</strong><small>${esc(r.text||'')}</small></button>`).join('')||'<div class="mini">لا توجد نتائج.</div>';box.querySelectorAll('[data-res]').forEach((el,i)=>el.onclick=()=>{const r=results.slice(0,40)[i];if(r.s){state.page=r.page;saveLocal();renderPages().then(()=>openAyah(r.s,r.a,r.page))}})}
const strip=s=>String(s||'').replace(/[ًٌٍَُِّْٰـ]/g,'').toLowerCase();

async function openDrawer(tab='index'){const d=document.getElementById('drawer');d.innerHTML=`<div class="scrim" data-action="closeDrawer"></div><aside class="drawer-card"><div class="drawer-head"><img src="./icons/samee3-logo.png"><div><b>مصحف سميع</b><small>المكتبة والقراءة</small></div><button class="icon" data-action="closeDrawer">✕</button></div><div class="drawer-nav"><button data-dtab="index">الفهرس</button><button data-dtab="juz">الأجزاء</button><button data-dtab="marks">المرجعيات</button><button data-dtab="notes">الملاحظات</button></div><div class="drawer-modules"><button data-action="mushaf">المصحف</button><button data-module="audio">المكتبة السمعية</button><button data-module="library">المكتبة المقروءة</button><button data-module="tools">أدوات المسلم</button>${state.admin?'<button data-action="admin">لوحة الإدارة</button>':''}</div><div id="drawerBody"></div></aside>`;d.classList.add('open');renderDrawerTab(tab);d.querySelectorAll('[data-dtab]').forEach(b=>b.onclick=()=>renderDrawerTab(b.dataset.dtab));}
function renderDrawerTab(tab){const body=document.getElementById('drawerBody');if(!body)return;if(tab==='index'){body.innerHTML=SURA_NAMES.map((n,i)=>`<button class="surah-row" data-goto="${i+1}"><div><b>${n}</b><small>السورة رقم ${i+1}</small></div><span>ص ${startPage(i+1)}</span></button>`).join('');body.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{goPage(startPage(+b.dataset.goto));closeDrawer()})}else if(tab==='juz'){body.innerHTML=Array.from({length:30},(_,i)=>`<details class="juz-row"><summary>الجزء ${i+1}</summary><div>${[1,2,3,4].map(q=>`<button data-jq="${i*2+1}">الربع ${q}</button>`).join('')}</div></details>`).join('');body.querySelectorAll('[data-jq]').forEach(b=>b.onclick=()=>{const juz=+b.dataset.jq;goPage(Math.min(604,Math.max(1,Math.round((juz-1)*20)+1)));closeDrawer()})}else if(tab==='marks'){const a=[...state.bookmarks].sort((x,y)=>y.date-x.date);body.innerHTML=`<div class="sort-row"><button data-sort="date">الأحدث</button><button data-sort="page">الصفحة</button></div>`+a.map(m=>`<button class="surah-row" data-mark="${esc(m.key)}"><div><b>${SURA_NAMES[m.surah-1]} — آية ${m.ayah}</b><small>صفحة ${m.page}</small></div><span>›</span></button>`).join('')||'<div class="mini">لا توجد مرجعيات.</div>';body.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>{const m=a.find(x=>x.key===b.dataset.mark);if(m){state.page=m.page;renderPages().then(()=>openAyah(m.surah,m.ayah,m.page));closeDrawer()}})}else{const a=[...state.notes].sort((x,y)=>y.date-x.date);body.innerHTML=`<div class="sort-row"><button>الأحدث</button><button>الصفحة</button></div>`+a.map(n=>`<div class="note-row"><b>${esc(n.text)}</b><small>${SURA_NAMES[n.surah-1]} • آية ${n.ayah} • ص ${n.page}</small></div>`).join('')||'<div class="mini">لا توجد ملاحظات.</div>'}}
function startPage(s){const starts=[1,2,50,77,106,128,151,177,187,208,221,235,249,255,262,267,282,293,305,312,322,332,342,350,359,367,376,385,396,404,410,414,418,429,434,440,446,453,459,467,477,483,489,496,502,507,511,515,517,519,521,525,527,529,532,534,537,539,541,543,545,548,550,552,553,555,557,559,561,562,564,565,567,568,570,571,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,589,590,591,592,593,594,595,596,597,598,599,600,601,601,602,602,603,603,604,604,604,604,604,604,604,604,604,604,604,604];return starts[Math.max(0,Math.min(113,s-1))]||1}

async function openSettings(){const s=document.getElementById('sheet');s.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card large"><div class="handle"></div><div class="sheet-head"><b>الإعدادات</b><button class="icon" data-action="closeSheet">✕</button></div><div class="setting-section"><h3>عام</h3><label>اللغة<select id="lang"><option value="ar">العربية</option><option value="en">English</option></select></label><label>التاريخ الهجري<input id="hijriOffset" type="number" value="0"></label></div><div class="setting-section"><h3>المظهر والقراءة</h3><div class="chips"><button data-theme="sepia">ورقي</button><button data-theme="ivory">عاجي</button><button data-theme="olive">زيتوني</button><button data-theme="dark">داكن</button></div><label>حجم الخط<input id="fontRange" type="range" min="15" max="28" value="${state.fontSize}"></label><button data-action="toggleWake">${state.settings.keepAwake?'✓':'○'} إبقاء الشاشة مضاءة</button><button data-action="toggleClock">${state.settings.showClock?'✓':'○'} إظهار الساعة</button><button data-action="toggleSide">${state.settings.sideTouch?'✓':'○'} اللمس الجانبي لتقليب الصفحات</button><button data-action="toggleHighlight">${state.settings.autoHighlight?'✓':'○'} تظليل وتتبع الآية</button><button data-action="toggleNext">${state.settings.autoNextPage?'✓':'○'} الانتقال للصفحة التالية</button></div><div class="setting-section"><h3>التنبيهات</h3><button>سورة الكهف</button><button>آية اليوم</button><button>تذكير الهجر</button><button>مواقيت الصلاة</button><button>الورد اليومي</button></div><div class="setting-section"><h3>التخزين</h3><button data-action="clearAudioCache">مسح التلاوات المحفوظة</button><button data-action="clearCache">مسح الكاش</button></div><div class="setting-section"><h3>تواصل معنا</h3><a class="whatsapp" href="https://wa.me/201005080532" target="_blank" rel="noopener">واتساب: 01005080532</a></div></section>`;s.classList.add('open');document.getElementById('fontRange').oninput=e=>{state.fontSize=+e.target.value;saveLocal();applyTheme();renderPages()};s.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;saveLocal();applyTheme()});}
async function setupWake(){if(state.settings.keepAwake&&'wakeLock'in navigator){try{window.__wake=await navigator.wakeLock.request('screen')}catch{}}else{try{await window.__wake?.release();window.__wake=null}catch{}}}
async function setupPrayer(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(async pos=>{try{const {latitude,longitude}=pos.coords;const d=await getJSON(`${API.prayer}/timings/${Math.floor(Date.now()/1000)}?latitude=${latitude}&longitude=${longitude}&method=4`);state.prayer=d.data;updatePrayerCountdown()}catch{}},()=>{});}
function updatePrayerCountdown(){const t=state.prayer?.timings;if(!t)return;const order=[['Fajr','الفجر'],['Dhuhr','الظهر'],['Asr','العصر'],['Maghrib','المغرب'],['Isha','العشاء']];const now=new Date();let next=order.map(([k,n])=>{const [h,m]=String(t[k]).split(':').map(Number);const d=new Date();d.setHours(h,m,0,0);return[n,d]}).find(x=>x[1]>now)||[order[0][1],new Date(Date.now()+86400000)];const rem=Math.max(0,next[1]-now);const hh=Math.floor(rem/3600000),mm=Math.floor(rem%3600000/60000),ss=Math.floor(rem%60000/1000);document.getElementById('prayerCountdown').textContent=`${next[0]} بعد ${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}:${String(ss).padStart(2,'0')}`}
setInterval(updatePrayerCountdown,1000);

async function accountModal(){const s=document.getElementById('sheet');if(state.user){s.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card"><div class="handle"></div><div class="sheet-head"><b>حسابي</b><button class="icon" data-action="closeSheet">✕</button></div><div class="account-card"><div>${esc(state.user.email||'')}</div><small>${state.admin?'مدير المنصة':'مستخدم'}</small></div><button class="gold-wide" data-action="sync">مزامنة الآن</button><button data-action="logout">تسجيل الخروج</button>${state.admin?'<button data-action="admin">فتح لوحة الإدارة</button>':''}</section>`}else{s.innerHTML=`<div class="scrim" data-action="closeSheet"></div><section class="sheet-card"><div class="handle"></div><div class="sheet-head"><b>تسجيل الدخول</b><button class="icon" data-action="closeSheet">✕</button></div><input id="authEmail" type="email" placeholder="البريد الإلكتروني"><input id="authPass" type="password" placeholder="كلمة المرور"><div class="row"><button class="gold-wide" data-action="login">دخول</button><button data-action="signup">إنشاء حساب</button></div><button data-action="reset">نسيت كلمة المرور</button></section>`}s.classList.add('open')}
async function login(){const e=document.getElementById('authEmail').value.trim(),p=document.getElementById('authPass').value;try{await signInWithEmailAndPassword(auth,e,p);closeSheet();showToast('تم تسجيل الدخول')}catch{showToast('تعذر تسجيل الدخول')}}
async function signup(){const e=document.getElementById('authEmail').value.trim(),p=document.getElementById('authPass').value;if(p.length<6)return showToast('كلمة المرور 6 أحرف على الأقل');try{await createUserWithEmailAndPassword(auth,e,p);closeSheet();showToast('تم إنشاء الحساب')}catch{showToast('تعذر إنشاء الحساب')}}
async function resetPass(){const e=document.getElementById('authEmail').value.trim();if(!e)return showToast('اكتب البريد أولًا');try{await sendPasswordResetEmail(auth,e);showToast('تم إرسال رابط الاستعادة')}catch{showToast('تعذر الإرسال')}}
async function checkAdmin(uid){try{const s=await getDoc(doc(db,'admins',uid));return s.exists()&&s.data().active===true}catch{return false}}
async function syncUserState(){if(!auth.currentUser)return;try{await setDoc(doc(db,'users',auth.currentUser.uid),{email:auth.currentUser.email,lastPage:state.page,riwayah:state.riwayah,fontSize:state.fontSize,theme:state.theme,bookmarks:state.bookmarks.slice(0,200),notes:state.notes.slice(0,200),playlists:state.playlists,updatedAt:serverTimestamp()},{merge:true})}catch{}}
async function pullUserState(){if(!auth.currentUser)return;try{const s=await getDoc(doc(db,'users',auth.currentUser.uid));if(!s.exists())return;const d=s.data();if(d.lastPage)state.page=d.lastPage;if(d.riwayah)state.riwayah=d.riwayah;if(d.fontSize)state.fontSize=d.fontSize;if(d.theme)state.theme=d.theme;if(Array.isArray(d.bookmarks))state.bookmarks=d.bookmarks;if(Array.isArray(d.notes))state.notes=d.notes;if(d.playlists)state.playlists=d.playlists;saveLocal();applyTheme();renderPages()}catch{}}

async function openAdmin(){if(!state.admin)return showToast('غير مصرح');const s=document.getElementById('module');document.getElementById('reader').hidden=true;s.hidden=false;s.innerHTML=`<div class="module-head"><div><h1>لوحة إدارة مصحف سميع</h1><p>إدارة إعدادات المنصة والإعلانات والمحتوى المميز.</p></div><button class="gold-wide" data-action="adminBack">المصحف</button></div><div class="admin-grid"><div class="admin-card"><h3>إعدادات المنصة</h3><label>اسم المنصة<input id="appName" value="مصحف سميع"></label><label>رسالة الترحيب<textarea id="welcome">أهلاً بك في مصحف سميع</textarea></label><button class="gold-wide" data-action="saveAdminConfig">حفظ</button></div><div class="admin-card"><h3>إعلان/تنبيه</h3><label>العنوان<input id="annTitle"></label><label>المحتوى<textarea id="annBody"></textarea></label><button class="gold-wide" data-action="saveAnnouncement">نشر</button></div><div class="admin-card"><h3>الوصول السريع</h3><button data-module="audio">المكتبة السمعية</button><button data-module="library">المكتبة المقروءة</button><button data-module="tools">أدوات المسلم</button></div></div>`;try{const d=await getDoc(doc(db,'appSettings','main'));if(d.exists()){document.getElementById('appName').value=d.data().appName||'مصحف سميع';document.getElementById('welcome').value=d.data().welcome||''}}catch{}}
async function saveAdminConfig(){try{await setDoc(doc(db,'appSettings','main'),{appName:document.getElementById('appName').value,welcome:document.getElementById('welcome').value,updatedAt:serverTimestamp()},{merge:true});showToast('تم الحفظ')}catch{showToast('تعذر الحفظ')}}
async function saveAnnouncement(){try{await setDoc(doc(db,'announcements',crypto.randomUUID()),{title:document.getElementById('annTitle').value,body:document.getElementById('annBody').value,createdAt:serverTimestamp(),active:true},{merge:true});showToast('تم نشر التنبيه')}catch{showToast('تعذر النشر')}}

async function openModule(name){const mod=document.getElementById('module');document.getElementById('reader').hidden=true;mod.hidden=false;mod.innerHTML='<div class="loader-page">جاري التحميل…</div>';if(name==='audio'){await openAudioModule()}else if(name==='library'){await openLibraryModule()}else if(name==='tools'){await openToolsModule()}}
async function openAudioModule(){const m=document.getElementById('module');await loadReciters();m.innerHTML=`<div class="module-head"><div><h1>المكتبة السمعية</h1><p>القراء والتلاوات من MP3Quran مباشرة.</p></div><button class="gold-wide" data-action="mushaf">المصحف</button></div><input id="audioSearch" class="search-big" placeholder="ابحث عن قارئ…"><div class="filter-chips">${Object.entries(RIWAYAT).map(([k,v])=>`<button data-ar="${k}">${v.label}</button>`).join('')}</div><div id="reciterCards" class="cards-grid"></div>`;const render=()=>{const q=strip(document.getElementById('audioSearch').value);const arr=filteredReciters().filter(r=>!q||strip(r.name).includes(q)||strip(r.readName).includes(q));document.getElementById('reciterCards').innerHTML=arr.slice(0,100).map((r,i)=>`<div class="reciter-card"><div><b>${esc(r.name)}</b><small>${esc(r.readName)}</small></div><div class="row"><button class="gold" data-rplay="${i}">تشغيل</button><button data-rdl="${i}">تنزيل</button></div></div>`).join('')||'<div class="mini">لا توجد تلاوات لهذه الرواية.</div>';document.querySelectorAll('[data-rplay]').forEach(b=>b.onclick=async()=>{const r=arr[+b.dataset.rplay];state.audio={r,sura:pageRows(state.page)[0]?.sura||1};const a=document.getElementById('audio');a.src=`${r.server}${page3(state.audio.sura)}.mp3`;a.play().catch(()=>{});document.getElementById('trackReciter').textContent=r.name;document.getElementById('trackSurah').textContent=SURA_NAMES[state.audio.sura-1];await loadTiming()});document.querySelectorAll('[data-rdl]').forEach(b=>b.onclick=async()=>{const r=arr[+b.dataset.rdl];try{const cache=await caches.open('samee3-audio-v1');for(const s of r.surahs.slice(0,114)){const u=`${r.server}${page3(s)}.mp3`;const resp=await fetch(u);await cache.put(u,resp)}showToast('تم حفظ التلاوة المتاحة لهذا القارئ')}catch{showToast('تعذر تحميل التلاوة')}})};document.getElementById('audioSearch').oninput=render;document.querySelectorAll('[data-ar]').forEach(b=>b.onclick=()=>{state.riwayah=b.dataset.ar;saveLocal();render()});render()}
async function openLibraryModule(){const m=document.getElementById('module');m.innerHTML=`<div class="module-head"><div><h1>المكتبة القرآنية والإسلامية</h1><p>التفسير والترجمات وكتب الحديث من مصادر مباشرة.</p></div><button class="gold-wide" data-action="mushaf">المصحف</button></div><div class="tabs"><button data-lib="tafsir" class="active">التفسير</button><button data-lib="translations">الترجمات</button><button data-lib="hadith">الحديث</button></div><div id="libraryBody"></div>`;m.querySelectorAll('[data-lib]').forEach(b=>b.onclick=()=>{m.querySelectorAll('[data-lib]').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadLibrary(b.dataset.lib)});loadLibrary('tafsir')}
async function loadLibrary(type){const b=document.getElementById('libraryBody');b.innerHTML='<div class="loader-page">جاري التحميل…</div>';if(type==='tafsir'){try{const r=await getJSON(`${API.qpedia}/search/${encodeURIComponent('تفسير')}/books`);const arr=(r.items||[]).slice(0,80);b.innerHTML=`<div class="cards-grid">${arr.map(x=>`<div class="book-card"><b>${esc(x.book_info?.name||x.name||'كتاب تفسير')}</b><small>${esc(x.book_info?.author||x.author||'')}</small><button data-tafsir="${x.book_info?.id||x.id||''}">فتح</button></div>`).join('')}</div>`}catch{b.innerHTML='<div class="error-card">تعذر تحميل فهرس التفاسير.</div>'}}else if(type==='translations'){try{const arr=await getJSON(`${API.qenc}/translations/list/?localization=ar`);b.innerHTML=`<div class="cards-grid">${(arr||[]).slice(0,150).map(x=>`<div class="book-card"><b>${esc(x.title)}</b><small>${esc(x.language_iso_code)} • ${esc(x.version)}</small><button data-trans="${esc(x.key)}">فتح سورة ${SURA_NAMES[(pageRows(state.page)[0]?.sura||1)-1]}</button></div>`).join('')}</div>`}catch{b.innerHTML='<div class="error-card">تعذر تحميل الترجمات.</div>'}}else{const editions=await getHadithEditions();const desired=[['الأربعين النووية',['ara-nawawi','ara-nawawis'] ],['صحيح البخاري',['ara-bukhari']],['صحيح مسلم',['ara-muslim']],['سنن أبي داود',['ara-abudawud']],['جامع الترمذي',['ara-tirmidhi']],['السنن الصغرى للنسائي',['ara-nasai']],['سنن ابن ماجه',['ara-ibnmajah']],['موطأ الإمام مالك',['ara-malik']],['مسند الإمام أحمد',['ara-ahmed']],['سنن الدارمي',['ara-darimi']]];const found=desired.map(([name,keys])=>{const key=keys.find(k=>editions.some(e=>e.name===k));return key?{name,key}:null}).filter(Boolean);b.innerHTML=`<div class="cards-grid">${found.map(x=>`<div class="book-card"><b>${x.name}</b><small>${x.key}</small><button data-hadith="${x.key}">فتح</button></div>`).join('')}</div>`;b.querySelectorAll('[data-hadith]').forEach(btn=>btn.onclick=()=>loadHadithBook(btn.dataset.hadith))}}
async function getHadithEditions(){const d=await getJSON(`${API.hadith}/editions.json`);return Object.keys(d).map(name=>({name}))}
async function loadHadithBook(key){const b=document.getElementById('libraryBody');b.innerHTML='<div class="loader-page">جاري تحميل الأحاديث…</div>';try{const d=await getJSON(`${API.hadith}/editions/${key}.json`);const arr=(d.hadiths||[]).slice(0,120);b.innerHTML=`<button data-action="backLibrary">← الكتب</button><h2>${esc(d.metadata?.name||key)}</h2>${arr.map(h=>`<article class="hadith-card"><small>رقم ${esc(h.hadithnumber)}</small><p>${esc(h.text)}</p></article>`).join('')}`; }catch{b.innerHTML='<div class="error-card">تعذر تحميل هذا الكتاب.</div>'}}
async function openToolsModule(){const m=document.getElementById('module');m.innerHTML=`<div class="module-head"><div><h1>أدوات المسلم</h1><p>الصلاة، الأذكار، الإحصائيات والختمة.</p></div><button class="gold-wide" data-action="mushaf">المصحف</button></div><div class="tools-grid"><div class="tool-card"><h3>أوقات الصلاة</h3><div id="prayerDetail">جاري الحساب…</div></div><div class="tool-card"><h3>الأذكار</h3><p>أذكار الصباح والمساء والنوم.</p><button class="gold-wide" data-action="azkar">فتح الأذكار</button></div><div class="tool-card"><h3>الإحصائيات</h3><b>${state.page} صفحة حالية</b><p>التقدم محفوظ محليًا ويمكن مزامنته مع الحساب.</p></div><div class="tool-card"><h3>الختمة</h3><p>خطط الختمة والتقدم اليومي.</p><button data-action="khatma">إنشاء خطة</button></div></div>`;if(state.prayer?.timings)document.getElementById('prayerDetail').textContent=`الفجر ${state.prayer.timings.Fajr} • الظهر ${state.prayer.timings.Dhuhr} • العصر ${state.prayer.timings.Asr} • المغرب ${state.prayer.timings.Maghrib} • العشاء ${state.prayer.timings.Isha}`}
async function openAzkar(){const m=document.getElementById('module');m.hidden=false;document.getElementById('reader').hidden=true;m.innerHTML='<div class="module-head"><div><h1>الأذكار</h1></div><button class="gold-wide" data-action="mushaf">المصحف</button></div><div id="azkarWrap" class="cards-grid"><div class="loader-page">جاري تحميل الأذكار…</div></div>';try{const d=await getJSON('https://raw.githubusercontent.com/asellam/HisnElMuslim/master/azkar.json');const arr=Array.isArray(d)?d:(d.azkar||[]);document.getElementById('azkarWrap').innerHTML=arr.slice(0,120).map((z,i)=>`<article class="zikr-card"><small>${esc(z.category||'حصن المسلم')}</small><p>${esc(z.content||z.text||'')}</p><b>التكرار: ${esc(z.count||1)}</b></article>`).join('')}catch{document.getElementById('azkarWrap').innerHTML='<div class="error-card">تعذر تحميل الأذكار حاليًا.</div>'}}
function openKhatma(){const days=Number(prompt('ختمة خلال كم يوم؟',30)||30);if(!days)return;const pagesPerDay=Math.ceil(604/days);localStorage.setItem('s3_khatma',JSON.stringify({days,pagesPerDay,start:Date.now()}));showToast(`تم إنشاء ختمة: ${pagesPerDay} صفحة يوميًا`)}

async function idbPut(storeName,key,value){return new Promise((resolve,reject)=>{const req=indexedDB.open('samee3-db',1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('audio'))d.createObjectStore('audio');};req.onsuccess=()=>{const dbx=req.result;const tx=dbx.transaction(storeName,'readwrite');tx.objectStore(storeName).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)};req.onerror=()=>reject(req.error)})}
async function clearAudioCache(){try{const c=await caches.delete('samee3-audio-v1');showToast(c?'تم مسح التلاوات المحفوظة':'لا يوجد كاش صوتي')}catch{}}
async function clearCache(){try{await caches.delete('samee3-static-v1');showToast('تم مسح كاش التطبيق')}catch{}}
function immersiveToggle(){state.immersive=!state.immersive;document.getElementById('topbar').classList.toggle('hidden',state.immersive);document.getElementById('player').classList.toggle('hidden',state.immersive);document.getElementById('immersiveHint').classList.toggle('hidden',!state.immersive)}
function setupEvents(){
 app.addEventListener('click',async e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;switch(a){case'menu':return openDrawer();case'closeDrawer':return document.getElementById('drawer').classList.remove('open');case'settings':return openSettings();case'account':return accountModal();case'search':return openSearch();case'prev':return prevPage();case'next':return nextPage();case'retry':return renderPages();case'closeSheet':return closeSheet();case'player':return openPlayer();case'play':return playSura();case'copyAyah':return copyAyah();case'shareAyah':return shareAyah();case'markAyah':return markAyah();case'noteAyah':return noteAyah();case'playAyah':return playCurrentAyah();case'repeatAyah':return repeatAyah();case'imageAyah':return imageAyah();case'tafseerAyah':return openEmbed('tafsir');case'toggleWake':state.settings.keepAwake=!state.settings.keepAwake;await setupWake();return openSettings();case'toggleClock':state.settings.showClock=!state.settings.showClock;return openSettings();case'toggleSide':state.settings.sideTouch=!state.settings.sideTouch;return openSettings();case'toggleHighlight':state.settings.autoHighlight=!state.settings.autoHighlight;return openSettings();case'toggleNext':state.settings.autoNextPage=!state.settings.autoNextPage;return openSettings();case'downloadCurrent':return downloadCurrent();case'repeatCurrent':return repeatAyah();case'repeatSegment':return showToast('اختر نطاق التلاوة من لوحة المشغل');case'clearAudioCache':return clearAudioCache();case'clearCache':return clearCache();case'login':return login();case'signup':return signup();case'reset':return resetPass();case'logout':await signOut(auth);closeSheet();return;case'sync':await syncUserState();return showToast('تمت المزامنة');case'admin':closeSheet();return openAdmin();case'adminBack':document.getElementById('module').hidden=true;document.getElementById('reader').hidden=false;return;case'saveAdminConfig':return saveAdminConfig();case'saveAnnouncement':return saveAnnouncement();case'mushaf':document.getElementById('module').hidden=true;document.getElementById('reader').hidden=false;return renderPages();case'azkar':return openAzkar();case'khatma':return openKhatma();case'backLibrary':return openLibraryModule();}});
 document.getElementById('reader').addEventListener('click',e=>{if(e.target.closest('.page'))return;if(window.innerWidth<900)immersiveToggle()});
 document.getElementById('drawer').addEventListener('click',e=>{const m=e.target.closest('[data-module]')?.dataset.module;if(m){document.getElementById('drawer').classList.remove('open');openModule(m)}});
 document.getElementById('reader').addEventListener('touchstart',e=>{state.swipeStartX=e.changedTouches[0].clientX},{passive:true});
 document.getElementById('reader').addEventListener('touchend',e=>{if(!state.swipeStartX)return;const dx=e.changedTouches[0].clientX-state.swipeStartX;state.swipeStartX=null;if(Math.abs(dx)>45){if(dx>0)prevPage();else nextPage()}} ,{passive:true});
 window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')nextPage();if(e.key==='ArrowRight')prevPage();if(e.key==='Escape'){document.querySelectorAll('.open').forEach(x=>x.classList.remove('open'))}});
 window.addEventListener('resize',()=>renderPages());
 const audio=document.getElementById('audio');audio.addEventListener('timeupdate',()=>{const r=document.getElementById('audioSeek');if(audio.duration)r.value=(audio.currentTime/audio.duration)*100;highlightByTime()});audio.addEventListener('ended',()=>{if(state.audio?.remaining>1){state.audio.remaining--;playCurrentAyah();return}if(state.settings.autoNextPage)nextPage()});document.getElementById('audioSeek').oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*(+e.target.value/100)};
}
function highlightByTime(){if(!state.settings.autoHighlight||!state.timings.length||!state.audio)return;const ms=document.getElementById('audio').currentTime*1000;const hit=state.timings.find(t=>ms>=Number(t.start_time)&&ms<Number(t.end_time));if(hit&&state.currentAyah?.[1]!==Number(hit.ayah)){state.currentAyah=[pageRows(state.page)[0]?.sura||1,Number(hit.ayah)];applyActiveAyah();const row=pageRows(state.page).find(r=>r.ayah===Number(hit.ayah));if(!row&&state.settings.autoNextPage){if(hit.page&&typeof hit.page==='string'){const m=hit.page.match(/(\d+)\.svg/);if(m)goPage(+m[1])}}}}

onAuthStateChanged(auth,async u=>{state.user=u;state.admin=u?await checkAdmin(u.uid):false;if(u)await pullUserState()});
async function boot(){layout();applyTheme();setupEvents();await setupPrayer();await loadReciters();await renderPages();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
boot();
